### PR TITLE
First test for string source functions

### PR DESCRIPTION
**Pull request by luk-f-a**
hi @stuartarchibald , this is a first test for string source functions. Please let me know if this is the type of test you had in mind and this is the right place for them. If all's good, don't merge for now. I'll add more tests to this PR.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for taking a look at this. I think the tests could be a mixture of what is present here and also make use of `exec` as controlling globals/freevars/locals is important to Numba because of compile time freezing of assumed constants. RE location of tests, where you've added this one is appropriate.

**Comment by luk-f-a** [comment]
@stuartarchibald  I have added two more batches of tests. Mostly I mirror the existing ones, but I'm not sure what the correct behaviour of `test_cache_invalidate` should be. Whenever you have time, please look at that case.

**Comment by stuartarchibald** [comment]
> @stuartarchibald I have added two more batches of tests. Mostly I mirror the existing ones, but I'm not sure what the correct behaviour of `test_cache_invalidate` should be. Whenever you have time, please look at that case.

Brilliant, thank you!

**Comment by stuartarchibald** [comment]
I'm going to merge these as is to get them into the PR build and we'll adjust them if needed. Thanks for working on this!

**Pull request merged**
